<?php
declare(strict_types=1);

return [
    [
        'slug' => 'northwind-settlement-platform',
        'client' => 'Northwind Bank',
        'title' => 'Replacing a settlement core without a single unplanned outage',
        'industry' => 'Financial Services', 'service' => 'Platform Engineering',
        'region' => 'Europe', 'duration' => '11 months', 'year' => '2025',
        'accent' => 'blue', 'layout' => 'dashboard', 'featured' => 1,
        'summary' => 'An event-sourced ledger took over from a thirty-year-old settlement core one domain at a time, clearing $11B a year at 99.99% availability.',
        'metrics' => [
            ['value' => '99.99%', 'label' => 'Settlement availability'],
            ['value' => '−54%', 'label' => 'Cost per transaction'],
            ['value' => '0', 'label' => 'Unplanned outages at cutover'],
            ['value' => '11', 'label' => 'Months end to end'],
        ],
        'challenge' => "Northwind's settlement core had been extended for three decades. It could not absorb real-time payment volumes, every change needed a six-week regression cycle, and the institutional knowledge to modify it safely had largely retired. A big-bang replacement had already been attempted once and abandoned.",
        'approach' => [
            ['title' => 'Prove parity before moving traffic', 'body' => 'An event-sourced ledger ran in shadow mode against production traffic for nine weeks. Every settlement was computed twice and reconciled automatically; we moved no traffic until the divergence rate held at zero for a full month-end close.'],
            ['title' => 'Strangle by domain, not by date', 'body' => 'Domestic transfers moved first, then direct debits, then cross-border. Each domain had its own cutover, its own rollback and its own reconciliation window, so a problem in one never threatened the others.'],
            ['title' => 'Make the change board unnecessary', 'body' => 'Automated controls generated the evidence the change advisory board had been reviewing by hand. Pre-approved change classes took releases off the critical path and moved cadence from six weeks to daily.'],
            ['title' => 'Hand over the pager', 'body' => 'Northwind engineers were embedded in the pod from month two and took primary on-call at month nine, two months before we left. Runbooks were written by the people who would use them.'],
        ],
        'outcome' => "The final domain cut over on a Tuesday afternoon with no customer-visible impact. The platform now clears $11B annually at 99.99% availability, cost per transaction fell by more than half, and Northwind's own team has shipped every release since handover.",
        'stack' => ['Event-sourced ledger', 'ISO 20022', 'Kafka', 'Kubernetes', 'Terraform', 'OpenTelemetry', 'PostgreSQL'],
        'quote' => 'They rebuilt our settlement platform without a single unplanned outage, and left our engineers able to run it. That second part is what nobody else delivered.',
        'quote_by' => 'Adaeze Okonkwo', 'quote_role' => 'Chief Technology Officer, Northwind Bank',
    ],
    [
        'slug' => 'arclight-storefront-replatform',
        'client' => 'Arclight Retail',
        'title' => 'A storefront rebuilt around the connection customers actually have',
        'industry' => 'Retail & Commerce', 'service' => 'Web & Commerce',
        'region' => 'Americas', 'duration' => '5 months', 'year' => '2026',
        'accent' => 'amber', 'layout' => 'commerce', 'featured' => 1,
        'summary' => 'Moving from a monolithic platform to an edge-rendered composable storefront cut LCP from 2.6s to 0.9s and lifted revenue per session 31%.',
        'metrics' => [
            ['value' => '0.9s', 'label' => 'LCP on throttled 4G'],
            ['value' => '+31%', 'label' => 'Revenue per session'],
            ['value' => '+2.8×', 'label' => 'Organic sessions'],
            ['value' => '5', 'label' => 'Months to full cutover'],
        ],
        'challenge' => "Arclight's storefront failed Core Web Vitals on every template. Sixty-eight percent of sessions were mobile, largely on mid-range Android devices, and the checkout abandoned at a rate the team had stopped trying to explain. A template change required a release train with a two-week lead time.",
        'approach' => [
            ['title' => 'Budget performance, then design to it', 'body' => 'We set an LCP budget of one second on a throttled 4G connection and enforced it in CI before writing a single template. Any commit that regressed the budget failed the build.'],
            ['title' => 'Decouple the front end', 'body' => 'An edge-rendered storefront with incremental regeneration kept catalogue pages instant while inventory and pricing stayed live through a thin commerce API.'],
            ['title' => 'Rebuild checkout around failure', 'body' => 'Three steps, no blocking third-party script, and a cart that survives a dropped connection. Every field was tested with real customers on real devices before it shipped.'],
            ['title' => 'Give merchandising back its autonomy', 'body' => 'Search relevance, ranking and campaign tooling moved into the merchandising team\'s hands. Campaign changes that took a release now take minutes.'],
        ],
        'outcome' => 'LCP fell from 2.6 seconds to 0.9. Revenue per session rose 31% within the first month and held. Organic sessions nearly tripled over twelve months as Core Web Vitals and structured data landed together.',
        'stack' => ['Composable commerce API', 'Edge rendering', 'Headless CMS', 'CDN image pipeline', 'Vector search', 'Experimentation platform'],
        'quote' => 'Our storefront went from a two and a half second LCP to under one second, and revenue per session moved with it inside the first month.',
        'quote_by' => 'Priya Raman', 'quote_role' => 'Head of Ecommerce, Arclight Retail',
    ],
    [
        'slug' => 'vantage-fleet-visibility',
        'client' => 'Vantage Logistics',
        'title' => 'Fleet visibility that holds up when the network does not',
        'industry' => 'Logistics', 'service' => 'Data & AI',
        'region' => 'Europe', 'duration' => '9 months', 'year' => '2025',
        'accent' => 'teal', 'layout' => 'dashboard', 'featured' => 1,
        'summary' => 'Ingesting telemetry from 92,000 vehicles with out-of-order tolerance cut empty running by 17% and ended the status phone calls.',
        'metrics' => [
            ['value' => '92k', 'label' => 'Vehicles tracked live'],
            ['value' => '−17%', 'label' => 'Empty running miles'],
            ['value' => '<400ms', 'label' => 'Ingest to dashboard'],
            ['value' => '−63%', 'label' => 'Status enquiry calls'],
        ],
        'challenge' => "Vantage's telemetry arrived late, out of order, or not at all. Planners worked around the system with spreadsheets, customers phoned for status the system already knew, and the warehouse and transport systems disagreed about basic facts like whether a load had left.",
        'approach' => [
            ['title' => 'Design for the real network', 'body' => 'Idempotent, out-of-order-tolerant ingestion with device-side buffering. A vehicle that drives through a dead zone for forty minutes reconciles cleanly when it reconnects.'],
            ['title' => 'Optimise against real constraints', 'body' => 'Routing respects driver hours, vehicle class, dock windows and urban access restrictions — the constraints planners were manually working around every morning.'],
            ['title' => 'Publish one truth', 'body' => 'Customer tracking reads the same event stream as operations. Support and customer can no longer see different states, which is what generated most of the calls.'],
            ['title' => 'Unify the vocabulary', 'body' => 'A shared domain model across WMS, TMS and telematics ended the daily reconciliation spreadsheets and the arguments they caused.'],
        ],
        'outcome' => 'Empty running fell 17% in the first two quarters. Status enquiry calls dropped by nearly two thirds. Estimate variance across the nine-month engagement was four percent.',
        'stack' => ['MQTT ingestion', 'Kafka', 'TimescaleDB', 'Constraint solver', 'Offline-first mobile', 'Kubernetes'],
        'quote' => 'The discovery was two weeks and the estimate held to within four percent across nine months. In this industry that is close to unheard of.',
        'quote_by' => 'Marcus Feld', 'quote_role' => 'VP Digital, Vantage Logistics',
    ],
    [
        'slug' => 'meridian-care-coordination',
        'client' => 'Meridian Health',
        'title' => 'One patient record across eleven disconnected clinical systems',
        'industry' => 'Healthcare', 'service' => 'Platform Engineering',
        'region' => 'Americas', 'duration' => '14 months', 'year' => '2025',
        'accent' => 'teal', 'layout' => 'grid', 'featured' => 0,
        'summary' => 'A FHIR-native integration layer unified EHR, laboratory and imaging feeds for 2.4M patients with zero reportable privacy incidents.',
        'metrics' => [
            ['value' => '2.4M', 'label' => 'Patients served'],
            ['value' => '−38%', 'label' => 'Time to first appointment'],
            ['value' => '0', 'label' => 'Reportable privacy incidents'],
            ['value' => '11', 'label' => 'Systems unified'],
        ],
        'challenge' => 'Meridian ran eleven clinical systems that did not agree on patient identity. Care coordinators reconciled records by hand, patients repeated their history at every step, and privacy controls existed as policy documents rather than enforced system behaviour.',
        'approach' => [
            ['title' => 'Normalise on FHIR', 'body' => 'A FHIR R4 integration layer mapped every source into one longitudinal record with provenance retained, so a clinician can always see where a fact came from.'],
            ['title' => 'Resolve identity probabilistically, review deterministically', 'body' => 'Probabilistic matching proposes merges; a trained human confirms anything below a strict confidence threshold. No record merges silently.'],
            ['title' => 'Make privacy a runtime property', 'body' => 'Purpose-bound access, field-level encryption and immutable access logs mean privacy is enforced by the system and provable from the logs, not asserted in a policy.'],
            ['title' => 'Gate on accessibility', 'body' => 'WCAG 2.2 AA checks block the pipeline, and an external audit signs off each major release. Patients on old devices and poor connections were the primary research cohort.'],
        ],
        'outcome' => 'Time to first appointment fell 38%. Care coordinators stopped reconciling by hand. Fourteen months in, the platform has had no reportable privacy incident and passes external accessibility audit on every release.',
        'stack' => ['HL7 FHIR R4', 'SMART on FHIR', 'PostgreSQL with RLS', 'Kubernetes', 'Vault', 'Terraform'],
        'quote' => 'For the first time our clinicians see one patient rather than eleven partial ones. That changed the work, not just the software.',
        'quote_by' => 'Dr. Helen Aturu', 'quote_role' => 'Chief Medical Information Officer, Meridian Health',
    ],
    [
        'slug' => 'helix-multi-tenant-platform',
        'client' => 'Helix Energy',
        'title' => 'Making an enterprise security review a form instead of a rebuild',
        'industry' => 'SaaS & Technology', 'service' => 'Cloud & DevSecOps',
        'region' => 'Americas', 'duration' => '7 months', 'year' => '2026',
        'accent' => 'violet', 'layout' => 'dashboard', 'featured' => 0,
        'summary' => 'Retrofitting tenancy, SSO, SCIM and audit export cut enterprise security review time by 63% and unblocked a stalled pipeline.',
        'metrics' => [
            ['value' => '−63%', 'label' => 'Security review time'],
            ['value' => '+41%', 'label' => 'Net revenue retention'],
            ['value' => '11 days', 'label' => 'Median enterprise onboarding'],
            ['value' => '7', 'label' => 'Months to delivery'],
        ],
        'challenge' => 'Helix had product-market fit and a pipeline it could not close. Tenancy had been bolted on after the first enterprise contract, SSO and SCIM did not exist, and every large deal stalled in security review for three to four months.',
        'approach' => [
            ['title' => 'Model tenancy at the data layer', 'body' => 'Isolation, residency and per-tenant configuration were re-modelled properly, then migrated behind a compatibility layer so no customer saw a disruption.'],
            ['title' => 'Ship the enterprise checklist as product', 'body' => 'SAML and OIDC SSO, SCIM provisioning, role management and audit export were built as first-class features, not per-deal services work.'],
            ['title' => 'Meter usage once', 'body' => 'A single usage event stream now feeds product limits, customer dashboards and invoicing, so the three numbers finally reconcile.'],
            ['title' => 'Turn pricing into configuration', 'body' => 'Entitlements became data. Helix has since launched four packaging changes without a release.'],
        ],
        'outcome' => 'Security review time fell 63%. Median enterprise onboarding is now eleven days. Net revenue retention rose 41% as expansion stopped being blocked by missing enterprise controls.',
        'stack' => ['Multi-tenant PostgreSQL', 'OIDC / SAML / SCIM', 'Usage event pipeline', 'Entitlement service', 'Kubernetes', 'Feature flags'],
        'quote' => 'We stopped losing deals in security review. That single change did more for revenue than a year of feature work.',
        'quote_by' => 'Tom Baptiste', 'quote_role' => 'VP Engineering, Helix Energy',
    ],
    [
        'slug' => 'civica-citizen-services',
        'client' => 'Civica',
        'title' => 'A citizen service that works on the first attempt, for everyone',
        'industry' => 'Public Sector', 'service' => 'Product Design',
        'region' => 'Europe', 'duration' => '8 months', 'year' => '2026',
        'accent' => 'blue', 'layout' => 'grid', 'featured' => 0,
        'summary' => 'Designing for assisted-digital users first took task completion to 96% and cut cost per transaction 44% across 1.9M transactions a year.',
        'metrics' => [
            ['value' => '96%', 'label' => 'Task completion rate'],
            ['value' => '−44%', 'label' => 'Cost per transaction'],
            ['value' => '1.9M', 'label' => 'Transactions per year'],
            ['value' => 'AA', 'label' => 'WCAG 2.2 verified'],
        ],
        'challenge' => 'The existing service was organised around the department rather than the citizen. Completion sat at 61%, the phone channel absorbed the failures, and an accessibility assessment had already been failed once.',
        'approach' => [
            ['title' => 'Research the hardest case first', 'body' => 'Discovery began with assisted-digital users, screen reader users and people on low-bandwidth connections. Everything that worked for them worked for everyone else.'],
            ['title' => 'Assure continuously', 'body' => 'Accessibility and service standard checks ran every sprint. Assessment confirmed what was already true rather than discovering problems late.'],
            ['title' => 'Isolate the legacy systems', 'body' => 'An anti-corruption layer let the citizen-facing service evolve weekly while the systems behind it changed on their own decade-long cadence.'],
            ['title' => 'Publish the numbers', 'body' => 'Completion rate, cost per transaction and availability went on a public dashboard from the first week of private beta.'],
        ],
        'outcome' => 'Task completion rose from 61% to 96%. Cost per transaction fell 44%. The service passed assessment first time and the phone channel now handles genuinely complex cases rather than digital failures.',
        'stack' => ['Progressive enhancement', 'Design system components', 'Anti-corruption layer', 'PostgreSQL', 'Terraform', 'Open telemetry'],
        'quote' => 'They designed for the people we usually fail, and the result worked better for absolutely everybody.',
        'quote_by' => 'Ruth Kelleher', 'quote_role' => 'Service Owner, Civica',
    ],
];
