<?php
declare(strict_types=1);

/** Marketplace catalogue. Every entry deploys through the Advanced Installer. */
return [
    [
        'slug' => 'atlas-corporate-platform',
        'name' => 'Atlas Corporate Platform',
        'tagline' => 'A complete multi-page corporate site with CMS, careers and investor sections.',
        'category' => 'websites', 'product_type' => 'website', 'layout' => 'hero',
        'price' => 349, 'compare_price' => 449, 'extended_price' => 899, 'enterprise_price' => 2400,
        'rating' => 4.9, 'reviews_count' => 214, 'sales_count' => 1840, 'version' => '3.2.1', 'lighthouse' => 99,
        'featured' => 1, 'released_at' => '2024-02-11', 'updated_at' => '2026-07-22',
        'tags' => ['Corporate', 'Multi-page', 'CMS', 'Careers'],
        'description' => "Atlas is the platform we deploy for enterprises that need a credible public face without a nine-month build. Eighteen composed page types, a headless-ready content layer, a careers module with structured-data job postings, and an investor relations section with document management.\n\nEvery page ships against a performance budget enforced in CI: sub-second LCP on a throttled 4G connection, zero layout shift, and a complete structured-data graph so search engines resolve your organisation as an entity rather than a set of pages.",
        'features' => ['18 composed page types', 'Headless CMS integration layer', 'Careers module with JobPosting schema', 'Investor relations document centre', 'Multi-language routing (12 locales)', 'Cookie consent and preference centre', 'Editorial workflow with draft previews', 'Automated sitemap and hreflang'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / MariaDB 10.6 / SQLite', 'Bundle size' => '46 KB gzipped', 'Lighthouse' => '99 / 100 / 100 / 100', 'Accessibility' => 'WCAG 2.2 AA verified', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Priority email support', 'Deployment playbook'],
        'pages' => ['Home', 'About', 'Services', 'Solutions', 'Case studies', 'Insights', 'Careers', 'Investors', 'Contact', 'Legal'],
        'demo_url' => '/marketplace/preview/atlas-corporate-platform',
    ],
    [
        'slug' => 'vertex-saas-starter',
        'name' => 'Vertex SaaS Starter',
        'tagline' => 'Marketing site, pricing engine and authenticated app shell for a SaaS launch.',
        'category' => 'websites', 'product_type' => 'website', 'layout' => 'dashboard',
        'price' => 429, 'compare_price' => null, 'extended_price' => 1100, 'enterprise_price' => 2900,
        'rating' => 4.8, 'reviews_count' => 176, 'sales_count' => 1320, 'version' => '2.8.0', 'lighthouse' => 98,
        'featured' => 1, 'released_at' => '2024-06-03', 'updated_at' => '2026-08-14',
        'tags' => ['SaaS', 'Pricing', 'Auth', 'Dashboard'],
        'description' => "Vertex is the full front half of a SaaS business: a conversion-tuned marketing site, a pricing engine that renders plans from configuration rather than markup, and an authenticated application shell with role-aware navigation already wired.\n\nThe entitlement model is data-driven, so launching a new plan is a configuration change instead of a release. Usage metering hooks are stubbed and documented, ready to point at your billing provider.",
        'features' => ['Configuration-driven pricing engine', 'Authenticated app shell with roles', 'Entitlement and plan gating', 'Usage metering hooks', 'Onboarding and empty states', 'Billing provider adapters', 'Changelog and status page', 'Docs section with search'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / PostgreSQL 14 / SQLite', 'Bundle size' => '52 KB gzipped', 'Lighthouse' => '98 / 100 / 100 / 100', 'Auth' => 'Sessions + optional OIDC', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Priority email support', 'Billing integration guide'],
        'pages' => ['Home', 'Pricing', 'Features', 'Docs', 'Changelog', 'Sign in', 'Sign up', 'App dashboard', 'Settings', 'Billing'],
        'demo_url' => '/marketplace/preview/vertex-saas-starter',
    ],
    [
        'slug' => 'meridian-commerce',
        'name' => 'Meridian Commerce',
        'tagline' => 'Composable storefront with catalogue, cart and a checkout built for slow networks.',
        'category' => 'ecommerce', 'product_type' => 'website', 'layout' => 'commerce',
        'price' => 549, 'compare_price' => 699, 'extended_price' => 1400, 'enterprise_price' => 3600,
        'rating' => 4.9, 'reviews_count' => 268, 'sales_count' => 2110, 'version' => '4.1.3', 'lighthouse' => 97,
        'featured' => 1, 'released_at' => '2023-11-19', 'updated_at' => '2026-08-30',
        'tags' => ['Commerce', 'Checkout', 'Catalogue', 'PWA'],
        'description' => "Meridian is a storefront engineered against the connection your customer actually has. Catalogue pages are statically rendered and revalidated, product media is served responsively from a CDN pipeline, and the checkout completes in three steps with no blocking third-party script.\n\nPayments, tax and shipping sit behind adapter interfaces, so swapping provider is a configuration change. The whole storefront runs offline-tolerant: the cart survives a dropped connection.",
        'features' => ['Static catalogue with revalidation', 'Three-step accessible checkout', 'Payment / tax / shipping adapters', 'Offline-tolerant cart', 'Faceted search and merchandising', 'Responsive CDN image pipeline', 'Abandoned-cart recovery hooks', 'Product schema and merchant feeds'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / MariaDB 10.6', 'Bundle size' => '58 KB gzipped', 'Lighthouse' => '97 / 100 / 100 / 100', 'Payments' => 'Adapter interface, 4 reference drivers', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Priority email support', 'Payment integration guide'],
        'pages' => ['Home', 'Catalogue', 'Product', 'Cart', 'Checkout', 'Account', 'Orders', 'Wishlist', 'Support', 'Legal'],
        'demo_url' => '/marketplace/preview/meridian-commerce',
    ],
    [
        'slug' => 'nimbus-admin-console',
        'name' => 'Nimbus Admin Console',
        'tagline' => 'Operations dashboard with tables, filters, roles and an audit trail.',
        'category' => 'dashboards', 'product_type' => 'template', 'layout' => 'dashboard',
        'price' => 289, 'compare_price' => null, 'extended_price' => 740, 'enterprise_price' => 1900,
        'rating' => 4.7, 'reviews_count' => 143, 'sales_count' => 980, 'version' => '2.4.0', 'lighthouse' => 99,
        'featured' => 0, 'released_at' => '2024-09-08', 'updated_at' => '2026-06-30',
        'tags' => ['Admin', 'Tables', 'RBAC', 'Audit'],
        'description' => "Nimbus is the internal console you would otherwise rebuild for the fourth time. Dense, sortable tables that degrade into readable cards on a phone, saved filter views, role-based access control, and an append-only audit trail on every mutation.\n\nThe table component handles fifty thousand rows without virtualisation tricks by paginating on the server and keeping the client payload under 30 KB.",
        'features' => ['Server-paginated data tables', 'Saved filter views per user', 'Role-based access control', 'Append-only audit trail', 'Bulk actions with confirmation', 'CSV and JSON export', 'Responsive card fallback', 'Keyboard-first navigation'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / PostgreSQL 14 / SQLite', 'Bundle size' => '38 KB gzipped', 'Lighthouse' => '99 / 100 / 100 / 100', 'Accessibility' => 'WCAG 2.2 AA verified', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Component documentation', '12 months of updates', 'Email support', 'RBAC configuration guide'],
        'pages' => ['Overview', 'Records', 'Detail', 'Users', 'Roles', 'Audit log', 'Reports', 'Settings'],
        'demo_url' => '/marketplace/preview/nimbus-admin-console',
    ],
    [
        'slug' => 'orbit-agency-theme',
        'name' => 'Orbit Agency Theme',
        'tagline' => 'A design-forward studio theme with case study layouts and motion built in.',
        'category' => 'themes', 'product_type' => 'theme', 'layout' => 'editorial',
        'price' => 189, 'compare_price' => 249, 'extended_price' => 480, 'enterprise_price' => 1200,
        'rating' => 4.8, 'reviews_count' => 312, 'sales_count' => 2740, 'version' => '5.0.2', 'lighthouse' => 98,
        'featured' => 1, 'released_at' => '2023-05-22', 'updated_at' => '2026-08-02',
        'tags' => ['Agency', 'Portfolio', 'Motion', 'Editorial'],
        'description' => "Orbit is for studios that are judged on their own site. Six case-study layouts, an editorial grid that holds up with real copy rather than lorem ipsum, and a motion system built entirely on transform and opacity so it stays smooth on a mid-range Android.\n\nEvery animation has a reduced-motion path and a touch equivalent, so the experience is designed rather than degraded on a phone.",
        'features' => ['6 case study layouts', 'Editorial grid system', 'GPU-only motion system', 'Reduced-motion and touch paths', 'Team and careers pages', 'Journal with topic taxonomy', 'Contact flow with qualification', 'Dark and light themes'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'SQLite / MySQL 8', 'Bundle size' => '31 KB gzipped', 'Lighthouse' => '98 / 100 / 100 / 100', 'Motion' => 'Transform + opacity only', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Email support', 'Motion guidelines'],
        'pages' => ['Home', 'Work', 'Case study', 'Services', 'Studio', 'Journal', 'Article', 'Contact'],
        'demo_url' => '/marketplace/preview/orbit-agency-theme',
    ],
    [
        'slug' => 'ledger-fintech-suite',
        'name' => 'Ledger Fintech Suite',
        'tagline' => 'Regulated-ready marketing site and customer portal for financial products.',
        'category' => 'websites', 'product_type' => 'website', 'layout' => 'hero',
        'price' => 699, 'compare_price' => null, 'extended_price' => 1800, 'enterprise_price' => 4800,
        'rating' => 4.9, 'reviews_count' => 88, 'sales_count' => 470, 'version' => '2.1.0', 'lighthouse' => 98,
        'featured' => 0, 'released_at' => '2025-01-30', 'updated_at' => '2026-08-19',
        'tags' => ['Fintech', 'Regulated', 'Portal', 'Compliance'],
        'description' => "Ledger is built for products that a regulator will read. Risk warnings and disclosures are content types with review workflow and effective dates, not hard-coded footers. The customer portal ships with statement delivery, document vaults and a complete access audit trail.\n\nConsent, cookie and marketing-preference records are queryable, exportable and versioned — the things you are asked for during an audit, available without a data project.",
        'features' => ['Disclosure content type with effective dates', 'Versioned consent and preference records', 'Customer portal with document vault', 'Statement delivery and archive', 'Complete access audit trail', 'Multi-entity and multi-jurisdiction routing', 'Accessibility statement generator', 'Data export for subject access requests'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / PostgreSQL 14', 'Bundle size' => '49 KB gzipped', 'Lighthouse' => '98 / 100 / 100 / 100', 'Compliance' => 'WCAG 2.2 AA, GDPR tooling', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '24 months of updates', 'Priority support with SLA', 'Compliance mapping document'],
        'pages' => ['Home', 'Products', 'Rates', 'Disclosures', 'Portal', 'Documents', 'Statements', 'Support', 'Legal'],
        'demo_url' => '/marketplace/preview/ledger-fintech-suite',
    ],
    [
        'slug' => 'clinic-health-portal',
        'name' => 'Clinic Health Portal',
        'tagline' => 'Patient-facing site and booking portal designed for accessibility first.',
        'category' => 'websites', 'product_type' => 'website', 'layout' => 'grid',
        'price' => 479, 'compare_price' => 579, 'extended_price' => 1250, 'enterprise_price' => 3200,
        'rating' => 4.8, 'reviews_count' => 121, 'sales_count' => 690, 'version' => '3.0.4', 'lighthouse' => 100,
        'featured' => 0, 'released_at' => '2024-08-27', 'updated_at' => '2026-07-11',
        'tags' => ['Healthcare', 'Booking', 'Accessible', 'Multi-site'],
        'description' => "Clinic is designed against the hardest case first: a patient in distress, on an old phone, on a poor connection. Every journey works without JavaScript, every form saves progress, and the whole site is verified to WCAG 2.2 AA on each release.\n\nBooking, clinician directories and location finders are multi-site aware, so a group with forty practices runs one deployment rather than forty.",
        'features' => ['Appointment booking with progress save', 'Clinician directory with filters', 'Multi-site and multi-location aware', 'Works fully without JavaScript', 'WCAG 2.2 AA verified per release', 'Symptom and service triage flows', 'Patient document delivery', 'Multi-language content'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / PostgreSQL 14', 'Bundle size' => '27 KB gzipped', 'Lighthouse' => '100 / 100 / 100 / 100', 'Accessibility' => 'WCAG 2.2 AA verified', 'Browsers' => 'Evergreen + Safari 14'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Priority email support', 'Accessibility audit report'],
        'pages' => ['Home', 'Services', 'Clinicians', 'Locations', 'Book', 'Patient portal', 'Documents', 'Contact', 'Accessibility'],
        'demo_url' => '/marketplace/preview/clinic-health-portal',
    ],
    [
        'slug' => 'signal-landing-kit',
        'name' => 'Signal Landing Kit',
        'tagline' => 'Twenty-four conversion-tested landing page templates with A/B hooks.',
        'category' => 'templates', 'product_type' => 'template', 'layout' => 'editorial',
        'price' => 129, 'compare_price' => 179, 'extended_price' => 340, 'enterprise_price' => 890,
        'rating' => 4.7, 'reviews_count' => 397, 'sales_count' => 3620, 'version' => '6.2.0', 'lighthouse' => 100,
        'featured' => 0, 'released_at' => '2023-03-14', 'updated_at' => '2026-08-25',
        'tags' => ['Landing', 'Conversion', 'A/B', 'Forms'],
        'description' => "Twenty-four landing page templates, each drawn from a campaign that actually ran. Long-form sales, webinar registration, gated content, waitlists, product launches and app installs — with the form patterns and social proof placements that tested best.\n\nExperiment hooks are wired for any A/B platform, and every template loads under 30 KB so paid traffic does not bounce before the hero paints.",
        'features' => ['24 campaign-tested templates', 'Experiment hooks for any A/B tool', 'Form patterns with inline validation', 'Under 30 KB per page', 'Consent-aware analytics hooks', 'Thank-you and nurture flows', 'Social proof component library', 'AMP-ready variants'],
        'specs' => ['Framework' => 'Static HTML + optional PHP', 'Database' => 'Not required', 'Bundle size' => '18 KB gzipped', 'Lighthouse' => '100 / 100 / 100 / 100', 'AMP' => 'Valid AMP variants included', 'Browsers' => 'Evergreen + Safari 14'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma files for all 24', '12 months of updates', 'Email support', 'Conversion playbook'],
        'pages' => ['24 landing templates', 'Thank-you pages', 'Form components', 'AMP variants'],
        'demo_url' => '/marketplace/preview/signal-landing-kit',
    ],
    [
        'slug' => 'harbor-logistics-tracker',
        'name' => 'Harbor Logistics Tracker',
        'tagline' => 'Customer-facing shipment tracking with a live operations view.',
        'category' => 'dashboards', 'product_type' => 'website', 'layout' => 'dashboard',
        'price' => 389, 'compare_price' => null, 'extended_price' => 990, 'enterprise_price' => 2600,
        'rating' => 4.6, 'reviews_count' => 74, 'sales_count' => 410, 'version' => '1.9.2', 'lighthouse' => 97,
        'featured' => 0, 'released_at' => '2025-04-16', 'updated_at' => '2026-05-28',
        'tags' => ['Logistics', 'Tracking', 'Realtime', 'Maps'],
        'description' => "Harbor gives customers the same shipment truth your operations team sees, which is the fastest way to stop the status phone calls. Tracking pages render from an event stream, tolerate out-of-order updates, and degrade to a readable timeline when the map cannot load.\n\nThe operations view adds exception queues, dwell alerts and a bulk-update workflow for dispatchers working on a tablet in a yard.",
        'features' => ['Event-sourced tracking timeline', 'Out-of-order update tolerance', 'Map with no-JS timeline fallback', 'Exception and dwell alert queues', 'Bulk dispatcher workflows', 'Proof-of-delivery capture', 'Customer notification templates', 'Public tracking API'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'MySQL 8 / PostgreSQL 14', 'Bundle size' => '44 KB gzipped', 'Lighthouse' => '97 / 100 / 100 / 100', 'Realtime' => 'SSE with polling fallback', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Email support', 'Integration guide for TMS feeds'],
        'pages' => ['Track', 'Timeline', 'Operations', 'Exceptions', 'Dispatch', 'Reports', 'Settings'],
        'demo_url' => '/marketplace/preview/harbor-logistics-tracker',
    ],
    [
        'slug' => 'quill-editorial-theme',
        'name' => 'Quill Editorial Theme',
        'tagline' => 'A publication theme with typography that holds up at ten thousand words.',
        'category' => 'themes', 'product_type' => 'theme', 'layout' => 'editorial',
        'price' => 149, 'compare_price' => null, 'extended_price' => 380, 'enterprise_price' => 980,
        'rating' => 4.9, 'reviews_count' => 256, 'sales_count' => 2180, 'version' => '4.3.1', 'lighthouse' => 100,
        'featured' => 0, 'released_at' => '2023-09-05', 'updated_at' => '2026-08-08',
        'tags' => ['Publishing', 'Typography', 'Newsletter', 'AMP'],
        'description' => "Quill is a reading experience first. A modular scale tuned for long-form, a measure that stays between 62 and 72 characters at every breakpoint, and footnotes, pull quotes, figures and data tables that all behave on a phone.\n\nArticles ship with valid AMP variants and a complete Article schema, and the newsletter module handles double opt-in and archive pages out of the box.",
        'features' => ['Long-form typographic scale', 'Footnotes, pull quotes, figures', 'Data tables that work on mobile', 'Valid AMP article variants', 'Newsletter with double opt-in', 'Author and topic archives', 'Reading progress and time estimates', 'Full Article structured data'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'SQLite / MySQL 8', 'Bundle size' => '22 KB gzipped', 'Lighthouse' => '100 / 100 / 100 / 100', 'AMP' => 'Valid AMP for every article', 'Browsers' => 'Evergreen + Safari 14'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '12 months of updates', 'Email support', 'Typography specification'],
        'pages' => ['Home', 'Article', 'Topic', 'Author', 'Archive', 'Newsletter', 'About', 'Contact'],
        'demo_url' => '/marketplace/preview/quill-editorial-theme',
    ],
    [
        'slug' => 'foundry-design-system',
        'name' => 'Foundry Design System',
        'tagline' => 'Tokens, components and documentation your engineers can consume as code.',
        'category' => 'templates', 'product_type' => 'template', 'layout' => 'grid',
        'price' => 249, 'compare_price' => 329, 'extended_price' => 640, 'enterprise_price' => 1700,
        'rating' => 4.8, 'reviews_count' => 189, 'sales_count' => 1470, 'version' => '3.5.0', 'lighthouse' => 99,
        'featured' => 0, 'released_at' => '2024-04-09', 'updated_at' => '2026-08-27',
        'tags' => ['Design system', 'Tokens', 'Components', 'Docs'],
        'description' => "Foundry is a design system delivered the way engineers can actually adopt it: a token layer that compiles to CSS custom properties, sixty-two components with documented states, and a documentation site that renders live examples from the same source as production.\n\nAccessibility is specified per component — roles, keyboard behaviour and focus order — so a review has something concrete to check against.",
        'features' => ['Token layer compiling to CSS variables', '62 documented components', 'Live example documentation site', 'Per-component accessibility spec', 'Dark and light themes from one source', 'Figma library kept in sync', 'Visual regression test suite', 'Contribution and versioning guide'],
        'specs' => ['Framework' => 'Framework-agnostic CSS + PHP partials', 'Database' => 'Not required', 'Bundle size' => '24 KB gzipped core', 'Lighthouse' => '99 / 100 / 100 / 100', 'Accessibility' => 'Per-component WCAG 2.2 AA spec', 'Browsers' => 'Evergreen + Safari 15'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma library', '12 months of updates', 'Email support', 'Adoption playbook'],
        'pages' => ['Overview', 'Tokens', 'Components', 'Patterns', 'Accessibility', 'Changelog'],
        'demo_url' => '/marketplace/preview/foundry-design-system',
    ],
    [
        'slug' => 'civic-services-platform',
        'name' => 'Civic Services Platform',
        'tagline' => 'Citizen service templates built to public service standards.',
        'category' => 'websites', 'product_type' => 'website', 'layout' => 'grid',
        'price' => 599, 'compare_price' => null, 'extended_price' => 1500, 'enterprise_price' => 3900,
        'rating' => 4.9, 'reviews_count' => 62, 'sales_count' => 310, 'version' => '2.0.1', 'lighthouse' => 100,
        'featured' => 0, 'released_at' => '2025-07-21', 'updated_at' => '2026-08-16',
        'tags' => ['Public sector', 'Forms', 'Accessible', 'Assisted digital'],
        'description' => "Civic is a set of citizen service patterns that pass assessment because they were built to the standard rather than retrofitted to it. Multi-step forms with save-and-return, plain-language error handling, and a full assisted-digital path for people who cannot complete the journey alone.\n\nA live performance dashboard publishes completion rate, cost per transaction and availability from day one, because publishing the numbers is part of the standard.",
        'features' => ['Multi-step forms with save and return', 'Assisted-digital and phone-agent paths', 'Plain-language error handling', 'Live performance dashboard', 'Works fully without JavaScript', 'WCAG 2.2 AA verified per release', 'Anti-corruption layer for legacy systems', 'Welsh and multi-language support'],
        'specs' => ['Framework' => 'Server-rendered PHP 8.2+', 'Database' => 'PostgreSQL 14 / MySQL 8', 'Bundle size' => '19 KB gzipped', 'Lighthouse' => '100 / 100 / 100 / 100', 'Accessibility' => 'WCAG 2.2 AA verified', 'Browsers' => 'Evergreen + Safari 14 + IE-safe fallbacks'],
        'includes' => ['Full source code', 'Advanced Installer package', 'Figma design system', '24 months of updates', 'Priority support with SLA', 'Service standard evidence pack'],
        'pages' => ['Start', 'Eligibility', 'Form steps', 'Check answers', 'Confirmation', 'Track', 'Performance', 'Accessibility'],
        'demo_url' => '/marketplace/preview/civic-services-platform',
    ],
];
