<?php
/**
 * SignalMasterAi - Base configuration.
 *
 * Do not edit this file for deployment settings. The step-by-step installer
 * (install.php) writes data/config.local.php with your choices, and all
 * runtime options (site name, API source, cache, thresholds, disclaimer...)
 * are editable from the admin panel and stored in the database.
 */

declare(strict_types=1);

if (!defined('SMA_ROOT')) {
    define('SMA_ROOT', __DIR__);
    // WHERE THE PRIVATE FILES LIVE, AND WHY IT IS NOT ALWAYS HERE.
    //
    // data/ ships inside the web root with an .htaccess denying it, and on a
    // great many hosts that .htaccess is never read: nginx does not read them
    // at all, and Apache ignores them unless AllowOverride is on. On those
    // servers the database - member emails, password hashes, API tokens,
    // payment records - is downloadable by anyone who asks for the URL. The
    // health check on the dashboard fetches the site's own URL to find out,
    // because the deny rule EXISTING and the deny rule WORKING are different
    // facts and only the second matters.
    //
    // The fix that works on every server, needing no server configuration at
    // all, is to keep the files somewhere the web server cannot serve. This
    // file is written by the admin panel when an operator moves them, and
    // holds one absolute path. It is checked rather than trusted: a path that
    // has gone missing falls back to the shipped location, so a half-finished
    // move or a restored backup leaves a site that still starts.
    $smaDataDir = SMA_ROOT . '/data';
    $smaPathFile = SMA_ROOT . '/data-path.php';
    if (is_file($smaPathFile)) {
        $smaCustom = require $smaPathFile;
        if (is_string($smaCustom) && $smaCustom !== '' && is_dir($smaCustom)) {
            $smaDataDir = rtrim($smaCustom, '/\\');
        }
    }
    define('SMA_DATA_DIR', $smaDataDir);
    define('SMA_LOCK_FILE', SMA_DATA_DIR . '/installed.lock');
    define('SMA_UPLOAD_DIR', SMA_DATA_DIR . '/uploads');
    unset($smaDataDir, $smaPathFile, $smaCustom);
}

$config = [
    'app_name'    => 'SignalMasterAi',
    'app_tagline' => 'AI-Powered Signals, Smarter Trading',

    // SQLite by default (zero configuration). The installer can switch this
    // to MySQL; its choice is saved in data/config.local.php.
    'db' => [
        'driver' => 'sqlite',
        'sqlite' => SMA_DATA_DIR . '/signalmasterai.sqlite',
        'mysql'  => [
            'host'     => '127.0.0.1',
            'port'     => 3306,
            'database' => 'signalmasterai',
            'username' => 'root',
            'password' => '',
            'charset'  => 'utf8mb4',
        ],
    ],

    // Free market data source: Binance public market-data REST API (no API key
    // required; the .vision host is not geo-restricted). All of these have live
    // overrides in the settings table (Admin > Settings).
    'market' => [
        'base_url'         => 'https://data-api.binance.vision',
        'cache_ttl'        => 300,
        'default_symbol'   => 'BTCUSDT',
        'default_interval' => '1h',
        'candle_limit'     => 500,
        'intervals'        => ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h',
                               '12h', '1d', '3d', '1w', '1mo'],
    ],

    'admin' => [
        'default_user'     => 'admin',
        // No default_password here any more. It was never read by anything -
        // the installer asks for a password, requires eight characters and a
        // confirmation, and hashes it - so the key did nothing except sit in
        // the one file an auditor opens first, next to the word "admin123".
        'session_name'     => 'sma_admin',
    ],
];

// Installer-written overrides (database choice, etc.)
$localFile = SMA_DATA_DIR . '/config.local.php';
if (is_file($localFile)) {
    $local = require $localFile;
    if (is_array($local)) {
        $config = array_replace_recursive($config, $local);
    }
}

return $config;
