<?php
/**
 * Copy of the config the installer writes. Do not edit this file — it is only
 * here so you can see what app/config.php looks like, and rebuild it by hand
 * if you ever need to.
 */
return [
    'driver'     => 'mysql',          // 'mysql' on real hosting, 'sqlite' locally
    'host'       => 'localhost',
    'port'       => '3306',
    'database'   => 'cpaneluser_techbiss',
    'username'   => 'cpaneluser_tb',
    'password'   => '',
    'sqlite_path'=> __DIR__ . '/../storage/techbiss.sqlite',
    'mail_from'  => 'website@yourdomain.com',
    'mail_to'    => 'hello@yourdomain.com',
    'base_url'   => '',               // e.g. https://techbiss.com — blank means auto-detect
    'app_key'    => '',               // random string, written at install
];
