<?php
/**
 * TECHBISS — configuration
 * This file is generated by the installer. Do not edit while installing.
 */
return [
    'db' => [
        'driver'   => 'mysql',
        'host'     => 'localhost',
        'port'     => 3306,
        'database' => '',
        'username' => '',
        'password' => '',
        'charset'  => 'utf8mb4',
    ],
    'app' => [
        'url'      => '',
        'timezone' => 'Asia/Kathmandu',
        'debug'    => false,
        'key'      => '',
    ],
    'mail' => [
        'from_name'  => 'TECHBISS',
        'from_email' => '',
    ],
];
