<?php
declare(strict_types=1);

return [
    'privacy' => [
        'title' => 'Privacy Notice',
        'summary' => 'What personal data TECHBISS collects, why we hold it, how long we keep it and the rights you can exercise.',
        'updated' => '2026-07-01',
        'body' => "<h2>Who we are</h2><p>TECHBISS Global Technologies is the data controller for personal data collected through this website and the platform services described on it. Our Data Protection Officer can be reached at <a href=\"mailto:privacy@techbiss.com\">privacy@techbiss.com</a>.</p><h2>What we collect</h2><ul><li><strong>Enquiry data.</strong> Name, work email, company, phone number and the content of your message, when you submit the contact form.</li><li><strong>Account data.</strong> Name, email, company and role for anyone with an admin, staff or client portal account, plus authentication events.</li><li><strong>Transaction data.</strong> Order references, licence keys and deployment records for marketplace purchases.</li><li><strong>Technical data.</strong> IP address and user agent, recorded against authentication attempts for security purposes.</li></ul><h2>Why we hold it</h2><p>Enquiry data is processed on the basis of legitimate interest in responding to business enquiries. Account and transaction data is processed to perform our contract with you. Security logging is processed on the basis of legitimate interest in protecting the platform.</p><h2>How long we keep it</h2><p>Enquiry data is retained for 24 months from last contact. Account and transaction data is retained for the life of the relationship plus seven years, to meet accounting obligations. Authentication logs are retained for 12 months.</p><h2>Who we share it with</h2><p>We do not sell personal data. We share it with infrastructure and payment providers acting as processors under contract, and with authorities where legally required. A current list of sub-processors is available on request.</p><h2>Your rights</h2><p>You may request access, correction, erasure, restriction or portability of your personal data, and object to processing based on legitimate interest. Contact <a href=\"mailto:privacy@techbiss.com\">privacy@techbiss.com</a>; we respond within 30 days. You may also complain to your national supervisory authority.</p><h2>International transfers</h2><p>We operate in four regions. Where data moves between them it is transferred under standard contractual clauses with supplementary technical measures, including encryption in transit and at rest.</p><h2>Cookies</h2><p>This site sets one strictly necessary cookie to maintain your session, and stores your theme preference in local storage. Neither is used for tracking or advertising. No third-party analytics or advertising script runs on this site.</p>",
    ],
    'terms' => [
        'title' => 'Terms of Service',
        'summary' => 'The terms governing use of the TECHBISS website, marketplace products and platform services.',
        'updated' => '2026-07-01',
        'body' => "<h2>Agreement</h2><p>These terms govern your use of this website, the TECHBISS Marketplace and any platform account issued to you. Consulting engagements are governed separately by their own statement of work, which prevails over these terms in the event of conflict.</p><h2>Accounts</h2><p>You are responsible for the confidentiality of your credentials and for activity under your account. Notify us immediately at <a href=\"mailto:security@techbiss.com\">security@techbiss.com</a> if you believe an account has been compromised. We may suspend an account that presents a security or legal risk.</p><h2>Marketplace licences</h2><p>Marketplace products are licensed, not sold. Each licence tier specifies the number of production sites, whether client work is permitted, and the support period. Redistribution, resale or sub-licensing of source code is prohibited under every tier unless separately agreed in writing.</p><h2>Payment and refunds</h2><p>Marketplace licences are payable in advance. Because products are delivered as source code, refunds are available within 14 days only where the product has not been deployed and the licence key has not been activated. Engagement fees are invoiced per the statement of work.</p><h2>Intellectual property</h2><p>For consulting engagements, all deliverables — source, infrastructure definitions, designs and documentation — are assigned to you on payment. For marketplace products, TECHBISS retains ownership and grants you the licence described in your tier.</p><h2>Warranties and liability</h2><p>We warrant that services will be performed with reasonable skill and care by suitably qualified personnel. Except as expressly stated, the website and marketplace products are provided as is. To the extent permitted by law, our aggregate liability is limited to the fees paid in the twelve months preceding the claim. Nothing limits liability for death, personal injury or fraud.</p><h2>Acceptable use</h2><p>You may not use the platform to store or transmit unlawful material, attempt to gain unauthorised access, interfere with its operation, or reverse engineer it other than as permitted by law.</p><h2>Governing law</h2><p>These terms are governed by the laws of England and Wales, and the courts of England and Wales have exclusive jurisdiction, without prejudice to mandatory consumer protections in your country of residence.</p>",
    ],
    'security' => [
        'title' => 'Security',
        'summary' => 'How the TECHBISS platform is secured, which frameworks we certify against, and how to report a vulnerability.',
        'updated' => '2026-08-12',
        'body' => "<h2>Programme</h2><p>Our security programme is run in-house by a dedicated CISO and security engineering team. We maintain SOC 2 Type II and ISO/IEC 27001 certification, both audited annually by an independent assessor. Reports are available under NDA.</p><h2>Platform controls</h2><ul><li><strong>Authentication.</strong> Passwords are hashed with a modern adaptive algorithm. Sign-in attempts are rate limited per account and per address, and session identifiers rotate on privilege change.</li><li><strong>Authorisation.</strong> Each portal accepts only the roles that belong to it; a credential valid for one portal cannot open another.</li><li><strong>Transport.</strong> HTTPS is enforced in production with modern cipher suites. Session cookies are HTTP-only, SameSite and secure.</li><li><strong>Request integrity.</strong> Every state-changing request carries a per-session CSRF token verified with a constant-time comparison.</li><li><strong>Injection.</strong> All database access uses prepared statements with bound parameters. All output is contextually escaped.</li><li><strong>Headers.</strong> Responses carry nosniff, frame-ancestors, referrer and permissions policies by default.</li></ul><h2>Development practice</h2><p>Threat modelling begins at architecture, not at audit. Dependencies are scanned continuously, and every release passes automated security checks before it can be deployed. Penetration testing is performed by an external firm before any major launch.</p><h2>Data protection</h2><p>Data is encrypted in transit and at rest. Access to production data requires a documented business reason, is time-bound, and is logged immutably. Backups are encrypted and restore-tested quarterly.</p><h2>Reporting a vulnerability</h2><p>Email <a href=\"mailto:security@techbiss.com\">security@techbiss.com</a> with reproduction steps. We acknowledge within one business day and aim to provide a remediation timeline within five. We will not pursue legal action against researchers acting in good faith who avoid privacy violations, service degradation and data destruction.</p>",
    ],
    'accessibility' => [
        'title' => 'Accessibility Statement',
        'summary' => 'The conformance level this platform meets, how it is tested, and how to report a barrier.',
        'updated' => '2026-08-20',
        'body' => "<h2>Conformance</h2><p>This platform is designed and tested to meet Web Content Accessibility Guidelines (WCAG) 2.2 Level AA. We assess conformance on every major release and publish the result internally against a fixed test plan.</p><h2>How we test</h2><ul><li>Automated checks run in the delivery pipeline and block a release on failure.</li><li>Manual keyboard-only testing of every interactive component each sprint.</li><li>Screen reader testing with NVDA on Windows and VoiceOver on macOS and iOS.</li><li>An independent external audit before each major release.</li></ul><h2>What we have done</h2><ul><li>All functionality is operable by keyboard, with a visible focus indicator and a skip link.</li><li>Colour contrast meets or exceeds 4.5:1 for body text and 3:1 for large text and interface components, in both light and dark themes.</li><li>Motion respects the reduced-motion preference; no animation is required to understand content.</li><li>Every interactive target is at least 44 by 44 CSS pixels on touch devices.</li><li>Forms use programmatically associated labels, inline error messages and clear instructions.</li><li>The site is fully usable with JavaScript disabled; enhancements are additive.</li></ul><h2>Known limitations</h2><p>Generated preview artwork is decorative and marked as such; it conveys no information not available in adjacent text. Complex data tables collapse into a stacked layout below 900 pixels, which changes reading order by design.</p><h2>Feedback</h2><p>If you encounter a barrier, email <a href=\"mailto:accessibility@techbiss.com\">accessibility@techbiss.com</a> with the page address and what happened. We aim to respond within two business days and to fix confirmed Level A and AA issues within one release cycle.</p>",
    ],
];
