<?php
declare(strict_types=1);

/** Industry solution pages. Each entry renders a full sub-page at /solutions/{slug}. */
return [
    [
        'slug' => 'financial-services',
        'name' => 'Financial Services',
        'category' => 'Regulated',
        'accent' => 'blue',
        'icon' => 'bank',
        'lede' => 'Core banking, payments and lending platforms that clear audit and clear traffic.',
        'summary' => 'Settlement rails, KYC/AML orchestration and customer platforms built for regulators, uptime and the cost per transaction your CFO watches.',
        'metrics' => [
            ['value' => '$11B', 'label' => 'Cleared annually on platforms we built'],
            ['value' => '99.99%', 'label' => 'Settlement availability'],
            ['value' => '−54%', 'label' => 'Cost per transaction'],
        ],
        'challenges' => [
            'Core systems that cannot absorb real-time payment volumes',
            'KYC and AML checks spread across incompatible vendors',
            'Audit evidence assembled by hand every quarter',
            'Release cadence throttled by change-advisory bottlenecks',
        ],
        'approach' => [
            ['title' => 'Strangle the core', 'body' => 'An event-sourced ledger runs alongside the legacy core, taking traffic domain by domain with reconciliation proving parity at every step.'],
            ['title' => 'Orchestrate compliance', 'body' => 'One decisioning layer fronts every KYC, AML and sanctions vendor, with a replayable audit trail and fallbacks per provider.'],
            ['title' => 'Automate the evidence', 'body' => 'Controls emit evidence continuously into the audit store, so a quarterly review is a query rather than a project.'],
            ['title' => 'Make releases boring', 'body' => 'Progressive delivery, automated controls and pre-approved change classes take the change board off the critical path.'],
        ],
        'stack' => ['Event-sourced ledger', 'ISO 20022 messaging', 'Kafka / Kinesis', 'Kubernetes', 'HashiCorp Vault', 'OpenTelemetry'],
        'compliance' => ['PCI DSS 4.0', 'SOC 2 Type II', 'PSD2 / SCA', 'ISO 27001', 'GDPR'],
        'proof' => 'northwind-settlement-platform',
    ],
    [
        'slug' => 'healthcare',
        'name' => 'Healthcare',
        'category' => 'Regulated',
        'accent' => 'teal',
        'icon' => 'pulse',
        'lede' => 'Clinical and patient platforms where privacy, uptime and clarity are all non-negotiable.',
        'summary' => 'Interoperable patient records, care coordination and virtual care built to HIPAA and WCAG 2.2 AA, with clinical safety cases documented as you go.',
        'metrics' => [
            ['value' => '2.4M', 'label' => 'Patients served on our platforms'],
            ['value' => '−38%', 'label' => 'Time to first appointment'],
            ['value' => '0', 'label' => 'Reportable privacy incidents'],
        ],
        'challenges' => [
            'Records fragmented across EHR, labs and imaging systems',
            'Patient journeys that assume a clinician is translating them',
            'Privacy controls proven by policy documents rather than by systems',
            'Accessibility treated as a launch-week retrofit',
        ],
        'approach' => [
            ['title' => 'Interoperate on FHIR', 'body' => 'A FHIR-native integration layer normalises EHR, laboratory and imaging feeds into one longitudinal record with provenance retained.'],
            ['title' => 'Design for the worst day', 'body' => 'Journeys are researched with patients in distress, on old devices and poor connections — not with staff on office laptops.'],
            ['title' => 'Prove privacy in code', 'body' => 'Purpose-bound access, field-level encryption and immutable access logs make privacy a runtime property, not a policy claim.'],
            ['title' => 'Accessibility as a gate', 'body' => 'WCAG 2.2 AA checks run in CI and block the pipeline; an external audit signs off each major release.'],
        ],
        'stack' => ['HL7 FHIR R4', 'SMART on FHIR', 'Postgres + row-level security', 'Kubernetes', 'Terraform', 'Grafana'],
        'compliance' => ['HIPAA', 'HITRUST-aligned', 'GDPR', 'WCAG 2.2 AA', 'ISO 27001'],
        'proof' => 'meridian-care-coordination',
    ],
    [
        'slug' => 'retail-commerce',
        'name' => 'Retail & Commerce',
        'category' => 'Commercial',
        'accent' => 'amber',
        'icon' => 'cart',
        'lede' => 'Composable storefronts measured on revenue per session and Core Web Vitals.',
        'summary' => 'Headless commerce, edge-rendered catalogue and a checkout engineered for the slow mobile network your best customer is actually on.',
        'metrics' => [
            ['value' => '+31%', 'label' => 'Revenue per session'],
            ['value' => '0.9s', 'label' => 'Largest Contentful Paint on 4G'],
            ['value' => '+2.8×', 'label' => 'Organic sessions in 12 months'],
        ],
        'challenges' => [
            'Monolithic platforms where a template change needs a release train',
            'Storefronts that fail Core Web Vitals on the devices customers use',
            'Promotions and pricing logic duplicated across channels',
            'Search and merchandising that cannot be tuned without a developer',
        ],
        'approach' => [
            ['title' => 'Decouple the front end', 'body' => 'An edge-rendered storefront with incremental static regeneration keeps catalogue pages instant while inventory stays live.'],
            ['title' => 'Centralise commerce logic', 'body' => 'Pricing, promotions and inventory move behind one commerce API consumed identically by web, app and store systems.'],
            ['title' => 'Budget the performance', 'body' => 'LCP, INP and CLS budgets are enforced in CI; a regression fails the build rather than the quarter.'],
            ['title' => 'Hand merchandising back', 'body' => 'Search relevance, ranking and campaign tooling move into the merchandiser\'s hands with no deploy required.'],
        ],
        'stack' => ['Composable commerce API', 'Edge rendering + ISR', 'Headless CMS', 'Vector search', 'CDN image pipeline', 'Experimentation platform'],
        'compliance' => ['PCI DSS 4.0', 'GDPR / CCPA', 'WCAG 2.2 AA', 'SOC 2 Type II'],
        'proof' => 'arclight-storefront-replatform',
    ],
    [
        'slug' => 'logistics',
        'name' => 'Logistics',
        'category' => 'Commercial',
        'accent' => 'blue',
        'icon' => 'route',
        'lede' => 'Fleet visibility and routing platforms that hold up when the network does not.',
        'summary' => 'Telemetry ingestion, route optimisation and customer-facing tracking engineered for intermittent connectivity and unforgiving margins.',
        'metrics' => [
            ['value' => '92k', 'label' => 'Vehicles tracked in real time'],
            ['value' => '−17%', 'label' => 'Empty running miles'],
            ['value' => '<400ms', 'label' => 'Telemetry ingest to dashboard'],
        ],
        'challenges' => [
            'Telemetry arriving late, out of order or not at all',
            'Route planning that ignores real-world driver constraints',
            'Customers phoning for status the system already knows',
            'Warehouse and transport systems that do not share a vocabulary',
        ],
        'approach' => [
            ['title' => 'Ingest for the real network', 'body' => 'Idempotent, out-of-order-tolerant ingestion with device-side buffering keeps the picture correct through dead zones.'],
            ['title' => 'Optimise with constraints', 'body' => 'Routing respects driver hours, vehicle class, dock windows and access restrictions — the constraints planners actually work around.'],
            ['title' => 'Publish the truth', 'body' => 'Customer tracking reads the same event stream operations does, so support and customer never see different states.'],
            ['title' => 'Unify the vocabulary', 'body' => 'A shared domain model across WMS, TMS and telematics ends the reconciliation spreadsheets.'],
        ],
        'stack' => ['MQTT / Kafka ingestion', 'Time-series store', 'Constraint solver', 'Offline-first mobile', 'Geospatial indexing', 'Kubernetes'],
        'compliance' => ['ISO 27001', 'GDPR', 'SOC 2 Type II'],
        'proof' => 'vantage-fleet-visibility',
    ],
    [
        'slug' => 'saas-technology',
        'name' => 'SaaS & Technology',
        'category' => 'Commercial',
        'accent' => 'violet',
        'icon' => 'cube',
        'lede' => 'Multi-tenant platforms built for the enterprise deal you have not closed yet.',
        'summary' => 'Tenancy, entitlements, SSO and usage metering designed once, correctly — so enterprise procurement becomes a form to fill in rather than a rebuild.',
        'metrics' => [
            ['value' => '−63%', 'label' => 'Enterprise security review time'],
            ['value' => '+41%', 'label' => 'Net revenue retention lift'],
            ['value' => '11 days', 'label' => 'Median enterprise onboarding'],
        ],
        'challenges' => [
            'Tenancy bolted on after the first enterprise contract',
            'SSO, SCIM and audit logs blocking six-figure deals',
            'Usage metering that billing and product disagree about',
            'A pricing model the codebase cannot express',
        ],
        'approach' => [
            ['title' => 'Get tenancy right once', 'body' => 'Isolation, residency and per-tenant configuration are modelled at the data layer before the first enterprise contract, not after.'],
            ['title' => 'Ship the enterprise checklist', 'body' => 'SAML/OIDC SSO, SCIM provisioning, audit export and role management delivered as first-class product, not services work.'],
            ['title' => 'Meter once', 'body' => 'One usage event stream feeds product limits, customer dashboards and invoicing, so the numbers always reconcile.'],
            ['title' => 'Make pricing a config', 'body' => 'Entitlements are data. New plans and packaging ship without a release.'],
        ],
        'stack' => ['Multi-tenant Postgres', 'OIDC / SAML / SCIM', 'Usage event pipeline', 'Entitlement service', 'Kubernetes', 'Feature flags'],
        'compliance' => ['SOC 2 Type II', 'ISO 27001', 'GDPR', 'Data residency controls'],
        'proof' => 'helix-multi-tenant-platform',
    ],
    [
        'slug' => 'public-sector',
        'name' => 'Public Sector',
        'category' => 'Regulated',
        'accent' => 'teal',
        'icon' => 'building',
        'lede' => 'Citizen services that work for everyone, on any device, on the first attempt.',
        'summary' => 'Accessible, resilient digital services delivered to public assurance standards, with cost and performance published rather than promised.',
        'metrics' => [
            ['value' => '1.9M', 'label' => 'Citizen transactions per year'],
            ['value' => '96%', 'label' => 'Task completion rate'],
            ['value' => '−44%', 'label' => 'Cost per transaction'],
        ],
        'challenges' => [
            'Services designed around the department, not the citizen',
            'Accessibility failures discovered at assessment',
            'Legacy systems with no safe integration path',
            'Procurement that outruns delivery capability',
        ],
        'approach' => [
            ['title' => 'Research the hardest case', 'body' => 'Discovery starts with assisted-digital and low-connectivity users; if it works for them it works for everyone.'],
            ['title' => 'Assure continuously', 'body' => 'Accessibility and service standard checks run every sprint, so assessment confirms what is already true.'],
            ['title' => 'Integrate safely', 'body' => 'An anti-corruption layer isolates legacy systems, letting the citizen-facing service evolve on its own cadence.'],
            ['title' => 'Publish the numbers', 'body' => 'Completion rate, cost per transaction and availability are published on a live dashboard from day one.'],
        ],
        'stack' => ['Progressive enhancement', 'Design system components', 'Anti-corruption layer', 'Open telemetry dashboards', 'Terraform', 'Postgres'],
        'compliance' => ['WCAG 2.2 AA', 'Service Standard', 'ISO 27001', 'GDPR / UK DPA'],
        'proof' => 'civica-citizen-services',
    ],
];
